/* Generated by vala-dbus-binding-tool 0.3.3. Do not modify! */
/* Generated with: vala-dbus-binding-tool -v -v -v --gdbus --no-synced --directory=. --strip-namespace=tp */
using GLib;

namespace org {

	namespace freedesktop {

		namespace Telepathy {

			namespace ChannelBundle {

				[DBus (name = "org.freedesktop.Telepathy.ChannelBundle.DRAFT", timeout = 120000)]
				public interface DRAFT : GLib.Object {
				}
			}
		}
	}
}
