/* Generated by vala-dbus-binding-tool 0.3.3. Do not modify! */
/* Generated with: vala-dbus-binding-tool -v -v -v --gdbus --no-synced --directory=. --strip-namespace=tp */
using GLib;

namespace org {

	namespace freedesktop {

		namespace Telepathy {

			namespace Call {

				namespace Content {

					namespace Interface {

						namespace Media {

							[DBus (name = "org.freedesktop.Telepathy.Call.Content.Interface.Media.DRAFT", timeout = 120000)]
							public interface DRAFT : GLib.Object {

								[DBus (name = "CodecsChanged")]
								public signal void codecs_changed(GLib.HashTable<uint, DRAFTUpdatedCodecStruct[]> Updated_Codecs, uint[] Removed_Contacts);

								[DBus (name = "UpdateCodecs")]
								public abstract void update_codecs(DRAFTCodecStruct[] Codecs) throws DBusError, IOError;

								[DBus (name = "NewCodecOffer")]
								public signal void new_codec_offer(uint Contact, GLib.ObjectPath Offer, DRAFTCodecStruct2[] Codecs);
							}
						}
					}
				}
			}
		}
	}
}
