/* Generated by vala-dbus-binding-tool 0.3.3. Do not modify! */
/* Generated with: vala-dbus-binding-tool -v -v -v --gdbus --no-synced --directory=. --strip-namespace=tp */
using GLib;

namespace org {

	namespace freedesktop {

		namespace Telepathy {

			namespace Call {

				namespace Stream {

					namespace Interface {

						namespace Media {

							[DBus (name = "org.freedesktop.Telepathy.Call.Stream.Interface.Media.DRAFT", timeout = 120000)]
							public interface DRAFT : GLib.Object {

								[DBus (name = "SetCredentials")]
								public abstract void set_credentials(string Username, string Password) throws DBusError, IOError;

								[DBus (name = "AddCandidates")]
								public abstract void add_candidates(DRAFTCandidateStruct[] Candidates) throws DBusError, IOError;

								[DBus (name = "CandidatesPrepared")]
								public abstract void candidates_prepared() throws DBusError, IOError;

								[DBus (name = "LocalCandidatesAdded")]
								public signal void local_candidates_added(DRAFTCandidateStruct2[] Candidates);

								[DBus (name = "LocalCredentialsChanged")]
								public signal void local_credentials_changed(string Username, string Password);

								[DBus (name = "RelayInfoChanged")]
								public signal void relay_info_changed(GLib.HashTable<string, GLib.Variant>[] Relay_Info);

								[DBus (name = "STUNServersChanged")]
								public signal void s_t_u_n_servers_changed(DRAFTServerStruct[] Servers);

								[DBus (name = "ServerInfoRetrieved")]
								public signal void server_info_retrieved();

								[DBus (name = "EndpointsChanged")]
								public signal void endpoints_changed(GLib.ObjectPath[] Endpoints_Added, GLib.ObjectPath[] Endpoints_Removed);

								[DBus (name = "PleaseRestartICE")]
								public signal void please_restart_i_c_e();
							}
						}
					}
				}
			}
		}
	}
}
