/* Generated by vala-dbus-binding-tool 0.3.3. Do not modify! */
/* Generated with: vala-dbus-binding-tool -v -v -v --gdbus --no-synced --directory=. --strip-namespace=tp */
using GLib;

namespace org {

	namespace freedesktop {

		namespace Telepathy {

			namespace Call {

				namespace Content {

					namespace CodecOffer {

						[DBus (name = "org.freedesktop.Telepathy.Call.Content.CodecOffer.DRAFT", timeout = 120000)]
						public interface DRAFT : GLib.Object {

							[DBus (name = "Accept")]
							public abstract void accept(DRAFTCodecStruct[] Codecs) throws DBusError, IOError;

							[DBus (name = "Reject")]
							public abstract void reject() throws DBusError, IOError;
						}
					}
				}
			}
		}
	}
}
