/* Generated by vala-dbus-binding-tool 0.3.3. Do not modify! */
/* Generated with: vala-dbus-binding-tool -v -v -v --gdbus --no-synced --directory=. --strip-namespace=tp */
using GLib;

namespace org {

	namespace freedesktop {

		namespace Telepathy {

			namespace Authentication {

				[DBus (name = "org.freedesktop.Telepathy.Authentication.TLSCertificate", timeout = 120000)]
				public interface TLSCertificate : GLib.Object {

					[DBus (name = "Accepted")]
					public signal void accepted();

					[DBus (name = "Rejected")]
					public signal void rejected(TLSCertificateRejectionStruct[] Rejections);

					[DBus (name = "Accept")]
					public abstract void accept() throws DBusError, IOError;

					[DBus (name = "Reject")]
					public abstract void reject(TLSCertificateRejectionStruct2[] Rejections) throws DBusError, IOError;
				}
			}
		}
	}
}
