/* Generated by vala-dbus-binding-tool 0.3.3. Do not modify! */
/* Generated with: vala-dbus-binding-tool -v -v -v --gdbus --no-synced --directory=. --strip-namespace=tp */
using GLib;

namespace org {

	namespace freedesktop {

		namespace Telepathy {

			namespace Call {

				namespace Content {

					namespace Interface {

						namespace Mute {

							[DBus (name = "org.freedesktop.Telepathy.Call.Content.Interface.Mute.DRAFT", timeout = 120000)]
							public interface DRAFT : GLib.Object {

								[DBus (name = "MuteStateChanged")]
								public signal void mute_state_changed(bool MuteState);

								[DBus (name = "SetMuted")]
								public abstract void set_muted(bool Muted) throws DBusError, IOError;
							}
						}
					}
				}
			}
		}
	}
}
