/* Generated by vala-dbus-binding-tool 0.3.3. Do not modify! */
/* Generated with: vala-dbus-binding-tool -v -v -v --gdbus --no-synced --directory=. --strip-namespace=tp */
using GLib;

namespace org {

	namespace freedesktop {

		namespace Telepathy {

			namespace Call {

				namespace Stream {

					namespace Endpoint {

						[DBus (name = "org.freedesktop.Telepathy.Call.Stream.Endpoint.DRAFT", timeout = 120000)]
						public interface DRAFT : GLib.Object {

							[DBus (name = "RemoteCredentialsSet")]
							public signal void remote_credentials_set(string Username, string Password);

							[DBus (name = "RemoteCandidatesAdded")]
							public signal void remote_candidates_added(DRAFTCandidateStruct[] Candidates);

							[DBus (name = "CandidateSelected")]
							public signal void candidate_selected(DRAFTCandidateStruct2 Candidate);

							[DBus (name = "SetSelectedCandidate")]
							public abstract void set_selected_candidate(DRAFTCandidateStruct23 Candidate) throws DBusError, IOError;

							[DBus (name = "StreamStateChanged")]
							public signal void stream_state_changed(uint state);

							[DBus (name = "SetStreamState")]
							public abstract void set_stream_state(uint State) throws DBusError, IOError;
						}
					}
				}
			}
		}
	}
}
